config/routes.rb
Deathstare::Engine.routes.draw do

  root 'test_sessions#new'

  # don't need :new since we already have root pointing at it
  resources :test_sessions, path:'sessions', only: [:create, :index, :show, :destroy] do
    collection do
      post :clear
    end
    member do
      get :stream
      post :cancel
    end
    resources :test_results, path:'results', only:[:index] do
      collection do
        get :errors
      end
    end
  end

  resources :end_points, only:[:index] do
    member do
      post :reset
    end
  end

  resource :concurrent_instances, only: [:show, :update]

  get 'login' => 'login#new'
  get '/auth/:provider/callback' => 'login#create'
  get 'logout' => 'login#destroy'
  get 'not_signed_in' => 'base#not_signed_in'

  #require 'sidekiq/web'

  #get '/sidekiq' => Sidekiq::Web.new

end

app/models/deathstare/end_point.rb
module Deathstare
  # Represents a single target end point. Multiple {TestSession} instances with the same base URL
  # will share an end point. End points are used to manage cached {UpstreamSession} records.
  class EndPoint < ActiveRecord::Base
    # Get a list of target URLs, this is used in the "End point" drop down in the web dashboard.
    # @return [Array<String>] list of end points
    def self.target_urls
      Deathstare.config.target_urls.dup.tap do |urls|
        urls.unshift 'http://localhost:3000' if Rails.env.development?
        urls.unshift 'http://test.host' if Rails.env.test?
      end
    end

    validates :base_url, inclusion: target_urls
    before_validation :set_defaults

    has_many :test_sessions, :dependent => :delete_all
    has_many :upstream_sessions, :dependent => :delete_all

    # Generate random client devices until the cache has the requested amount.
    # If there are already enough devices in the cache this will be a no-op.
    #
    # @param device_count [Integer] number of devices to create
    # @yieldparam progress [String] periodically yields progress for logging
    # @return [void]
    def generate_devices device_count
      return if upstream_sessions.count >= device_count
      print "Generating #{device_count} devices..." if Rails.env.development?
      needed_devices = device_count - upstream_sessions.count
      needed_devices.times.each do |i|
        generate_upstream_session
        report_progress = (needed_devices >= 10) && (i % (needed_devices/10).to_i == 0)
        yield "Generated #{i} devices." if report_progress && block_given?
      end
      puts 'done.' if Rails.env.development?
    end

    # Ensure every generate client device has a session token, register and login
    # the ones that don't. This method blocks until it's completed.
    #
    # @param client [Client]
    # @param success [Proc] success callback
    # @param failure [Proc] failure callback
    # @return [void]
    def register_and_login_devices client, success=nil, failure=nil, &callback
      success ||= callback
      upstream_sessions.state(nil).each do |session|
        session.register_and_login(client).then success, failure
      end
      client.run
    end

    # Clear the upstream session cache. This is needed whenever the upstream end point is reset.
    # @return [void]
    def clear_upstream_sessions
      upstream_sessions.delete_all
    end

    private

    def generate_upstream_session
      session = nil
      until session && session.save # make sure we get a valid device
        session = (Deathstare.config.upstream_session_type || UpstreamSession).generate(self)
      end
      session
    end

    def set_defaults
      self.base_url = self.class.target_urls.first if self.base_url.blank?
    end
  end
end

app/models/deathstare/heroku_app.rb
module Deathstare
  class HerokuApp

    # @abstract Heroku doesn't reject people from logging in even if they aren't members on the app
    #   They'll get an API token anyway. However, every subsequent call to the API fails with a 403
    #   (forbidden) -- that's how we can tell they're not a legit user.
    # @param user [User] -- authenticated User with Heroku OAuth token and/or refresh token
    def self.user_authorized_for_app? user
      HerokuApiV3.get(user: user, url: "/apps/#{Deathstare.config.heroku_app_id}")
      true
    rescue HerokuApiV3::UnauthorizedAppError
      false
    end

    # @param user [User] -- authenticated User with Heroku OAuth token and/or refresh token
    # @param requested [Integer or String] Number of sidekiq workers requested
    def self.scale_sidekiq_workers(user, requested)
      HerokuApiV3.patch(
        user: user,
        url: "/apps/#{Deathstare.config.heroku_app_id}/formation/sidekiq",
        body: {quantity: requested}
      )
    end

    # @param user [User] -- authenticated User with Heroku OAuth token and/or refresh token
    # @return [Integer] Number of sidekiq processes in "up" state
    def self.get_number_running_sidekiq_workers(user)
      # Sadly the formation API doesn't give us the status
      # And the dyno API won't let us query by type :-(
      # So we get all dynos and filter in Ruby
      dynos = HerokuApiV3.get(
        user: user,
        url: "/apps/#{Deathstare.config.heroku_app_id}/dynos"
      )
      dynos.count { |dyno| dyno['type'] == 'sidekiq' && dyno['state'] == 'up' }
    end
  end
end

app/models/deathstare/test_result.rb
require 'yajl'

class Deathstare::TestResult < ActiveRecord::Base
  belongs_to :test_session
  validates :test_session_id, :suite_name, :test_name, presence: true

  class << self
    # @param suite_name [String] Suite name
    # @param test_name [String] Test name
    # @param response [Hash] response hash from DSClient
    def from_response suite_name, test_name, response
      new(
        suite_name: suite_name,
        test_name: test_name,
        messages: response_message(response).tap {|msg| puts(msg) if Rails.env.development? }
      )
    end

    # Create a log message given a response Hash.
    def response_message response
      "%s %s: %s %s (%f)\n%s" % [
        *response[:_response_meta].slice(
          :request_method, :request_url, :status_code, :status_message, :total_time
        ).values,
        Yajl::Encoder.encode(response.except(:_response_meta))
      ]
    end
  end
end

app/models/deathstare/user.rb
module Deathstare
  class User < ActiveRecord::Base

    validates :oauth_provider, :uid, presence: true

  end
end

app/controllers/deathstare/application_controller.rb
module Deathstare
  class ApplicationController < ActionController::Base
    include Deathstare::CurrentUser

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    # This shouldn't be happening any more--> we try to refresh tokens if they're expired or about to expire
    rescue_from HerokuApiV3::ExpiredTokenError, with: :token_expired

    force_ssl if: -> { Rails.env.production? }
    before_action :ensure_signed_in!, except: :not_signed_in # production only

    def not_signed_in
      redirect_to root_path if signed_in?
    end

    protected

    def token_expired
      session[:user_id] = nil
      respond_to do |fmt|
        fmt.html { redirect_to not_signed_in_path, alert: 'Heroku session has expired. Please sign in.' }
        fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
      end
    end

    def can_control_scalability?
      Rails.env.production?
    end

    private

    def ensure_signed_in!
      if !signed_in? && Rails.env.production?
        respond_to do |fmt|
          fmt.html { redirect_to not_signed_in_path, alert: 'Please sign in.' }
          fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
        end
      end
    end
  end
end

app/controllers/deathstare/base_controller.rb
module Deathstare
  class BaseController < ApplicationController
    include Deathstare::CurrentUser

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    # This shouldn't be happening any more--> we try to refresh tokens if they're expired or about to expire
    rescue_from HerokuApiV3::ExpiredTokenError, with: :token_expired

    force_ssl if: -> { Rails.env.production? }
    before_action :ensure_signed_in!, except: :not_signed_in # production only

    def not_signed_in
      redirect_to root_path if signed_in?
    end

    protected

    def token_expired
      session[:user_id] = nil
      respond_to do |fmt|
        fmt.html { redirect_to not_signed_in_path, alert: 'Heroku session has expired. Please sign in.' }
        fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
      end
    end

    def can_control_scalability?
      Rails.env.production?
    end

    private

    def ensure_signed_in!
      if !signed_in? && Rails.env.production?
        respond_to do |fmt|
          fmt.html { redirect_to not_signed_in_path, alert: 'Please sign in.' }
          fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
        end
      end
    end
  end
end

app/controllers/deathstare/concurrent_instances_controller.rb
module Deathstare
  class ConcurrentInstancesController < Deathstare::BaseController
    def show
      if signed_in?
        num = HerokuApp.get_number_running_sidekiq_workers current_user
        render json: {actual: num}, status: 200
      elsif Rails.env.development?
        render json: {actual: 1}, status: 200
      else
        render json: {actual: 0}, status: 200
      end
    end

    def update
      if can_control_scalability?
        HerokuApp.scale_sidekiq_workers(current_user, params[:requested])
        render json: {requested: params[:requested]}, status: 200
      else
        render json: {error: 'Can only scale workers in production environment'}, status: 412
      end
    end

  end
end

app/controllers/deathstare/end_points_controller.rb
module Deathstare
  class EndPointsController < BaseController
    def index
      @end_points = EndPoint.all
    end

    def reset
      end_point.clear_upstream_sessions
      flash[:notice] = "Cleared cache of devices and sessions for #{end_point.base_url}."
      redirect_to end_points_path
    end

    private

    def end_point
      EndPoint.find params[:id]
    end
  end
end

app/controllers/deathstare/login_controller.rb
module Deathstare
  class LoginController < BaseController

    skip_before_action :ensure_signed_in!, except: :destroy

    def new
      redirect_to '/auth/heroku'
    end

    def create
      omniauth = request.env['omniauth.auth']
      @current_user = User.find_or_create_by!(oauth_provider: omniauth['provider'], uid: omniauth['uid'])
      @current_user.token = omniauth['credentials']['token']
      @current_user.token_expires_at = !!omniauth['credentials']['expires'] ? Time.at(omniauth['credentials']['expires_at']) : nil
      @current_user.refresh_token = omniauth['credentials']['refresh_token']
      @current_user.save!
      if HerokuApp.user_authorized_for_app?(@current_user)
        session[:user_id] = @current_user.id
        redirect_to root_path, notice: 'Signed in with Heroku'
      else
        @current_user.authorized_for_app = false
        @current_user = nil
        session[:user_id] = nil
        redirect_to root_path, alert: "You are not authorized on this app. If you're a member of Cloud City Development, talk to the administrator."
      end
    end

    def destroy
      @current_user = nil
      session[:user_id] = nil
      redirect_to root_path, notice: 'Ended Heroku OAuth Session'
    end
  end
end

app/controllers/deathstare/test_results_controller.rb
module Deathstare
  class TestResultsController < BaseController
    def index
      @title = "Result Log"
      @test_session = test_session
      @test_results = @test_session.test_results.order('created_at DESC').paginate(page: params[:page], per_page: 100)
    end

    def errors
      @title = "Error Log"
      @test_session = test_session
      @test_results = @test_session.test_errors.order('created_at DESC').paginate(page: params[:page], per_page: 100)
      render action:'index'
    end

    private

    def test_session
      TestSession.find params[:test_session_id]
    end
  end
end

app/controllers/deathstare/test_sessions_controller.rb
module Deathstare
  require 'librato/librato_app'

  class TestSessionsController < BaseController
    before_action :load_resource, only: [:show, :stream, :cancel, :destroy]

    def index
      @test_sessions = TestSession.order(id: :desc).paginate(page:params[:page])
      # TODO: List here links to the show pages of previous runs
    end

    def new
      @test_session = TestSession.new_with_defaults
    end

    def create
      params.permit!

      worker_count = \
        if Rails.env.development? || Rails.env.test?
          1
        elsif signed_in?
          HerokuApp.get_number_running_sidekiq_workers(current_user)
        else
          0
        end

      if worker_count == 0
        flash.alert = "Start at least one worker instance per Suite being tested."
        redirect_to action: 'new'
        return
      end

      @test_session = TestSession.create(params[:test_session].merge(workers:worker_count, user:current_user))
      if @test_session.persisted?
        @test_session.enqueue
        redirect_to @test_session
      else
        flash.alert = "Failed to create session: #{@test_session.errors.full_messages.join(' ')}"
        redirect_to action: 'new'
      end
    end

    def show
      load_resource
      @live_instrument_ids = LibratoApp.create_or_update_instruments(@test_session.suite_names)
      respond_to do |format|
        format.html { render 'show' }
        format.json { render json: @live_instrument_ids }
      end
    end

    def cancel
      if @test_session.cancel_session
        flash.notice = "You've cancelled session ##{@test_session.id}."
      else
        flash.alert = "Failed to cancel session ##{@test_session.id}!"
      end
      redirect_to @test_session
    end

    def destroy
      if !@test_session.ended?
        flash.alert = "This session is still running, cancel it first."
      elsif @test_session.destroy
        flash.notice = "Removed session ##{@test_session.id}."
      else
        flash.alert = "Failed to remove session ##{@test_session.id}."
      end
      redirect_to action:'index'
    end

    def clear
      if Deathstare::TestSession.running.any?
        flash.alert = "There is a running session, cancel it first."
        redirect_to action:'index'
      else
        Deathstare::TestSession.destroy_all
        flash.notice = "Removed all previous sessions."
        redirect_to action:'new'
      end
    end

    private

    def load_resource
      @test_session = TestSession.find(params[:id])
    end

  end
end

app/helpers/deathstare/application_helper.rb
module Deathstare
  module ApplicationHelper
    # Return HTML to support a pretty-printed date.
    #
    # @param date [DateTime] some date in the past
    # @return [String] HTML span representing a friendly-formatted date
    def relative_date date
      %[<span class="relative-date" title="#{date.iso8601}">#{date}</span>].html_safe
    end

    # @param test_session [TestSession] test session
    # @return [String] Friendly list of suite classes, or "All"
    def suites test_session
      test_session.suite_names.join(', ').tap{|t| t.prepend('All') if t.empty? }
    end
  end
end

app/helpers/deathstare/base_helper.rb
module Deathstare
  module BaseHelper
    # Return HTML to support a pretty-printed date.
    #
    # @param date [DateTime] some date in the past
    # @return [String] HTML span representing a friendly-formatted date
    def relative_date date
      %[<span class="relative-date" title="#{date.iso8601}">#{date}</span>].html_safe
    end

    # @param test_session [TestSession] test session
    # @return [String] Friendly list of suite classes, or "All"
    def suites test_session
      test_session.suite_names.join(', ').tap{|t| t.prepend('All') if t.empty? }
    end
  end
end

app/views/deathstare/test_sessions/_details.html.haml
- if !@test_session.comment.blank?
  %p
    = @test_session.comment

%p
  Targeting
  %strong
    = @test_session.base_url
  for
  %strong
    at least
    = @test_session.run_time
    seconds per test
  with
  %strong
    = @test_session.workers
    workers
  and
  %strong
    = @test_session.devices
    concurrent devices per worker

app/views/deathstare/test_sessions/index.html.haml
%h1 Previous Test Runs

- if @test_sessions.count > 0
  %p= link_to "Remove All", clear_test_sessions_path,
    method:'POST', confirm:'Remove all previous session records?'

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %td ID
      %td Started
      %td Suites
      %td End Point
      %td{title:"Minimum Run Time in seconds"} Run Time
      %td Workers
      %td{title:"Concurrent devices per worker"} Devices
      %td per sec
      %td Successes
      %td Bad %
      %td Errors
      -#%td Average
      -#%td Min
      -#%td Max
      %td
  %tbody
    - @test_sessions.each do |run|
      %tr
        %td= link_to run.id, test_session_test_results_path(run), title: 'Detailed Responses'
        %td
          -if run.started?
            = relative_date(run.started_at)
          -else
            Warming up...
        %td= link_to suites(run), test_session_path(run), title: 'Chart'
        %td= run.base_url.sub('http://','')
        %td= run.elapsed_time
        %td= run.workers
        %td= run.devices
        %td
          -if run.elapsed_time > 0
            = ((run.test_successes.count + run.test_errors.count).to_f / ( run.elapsed_time )).to_i
          -else
            = ''
        %td= run.result_count
        %td
          -if (run.test_successes.count + run.test_errors.count).to_f > 0
            = ((run.test_errors.count.to_f / (run.test_successes.count + run.test_errors.count).to_f) * 100.0).ceil
          -else
            = ''
        %td= link_to run.test_errors.count, errors_test_session_test_results_path(run)
        -#%td= "(XXX Librato)"
        -#%td= "(XXX Librato)"
        -#%td= "(XXX Librato)"
        %td
          -if run.running?
            = link_to "Cancel", cancel_test_session_path(run),
              method:'POST', confirm:'This session is running. Cancel it?'
          -else
            = link_to "Remove", test_session_path(run),
              method:'DELETE', confirm:'Remove all record of this session?'


= will_paginate @test_sessions

app/views/deathstare/test_sessions/new.html.haml
-# TODO: Put an error explanation here, see: http://guides.rubyonrails.org/active_record_validations.html#displaying-validation-errors-in-views
-#<% if @post.errors.any? %>
-#  <div id="error_explanation">
-#    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
-#
-#    <ul>
-#    <% @post.errors.full_messages.each do |msg| %>
-#      <li><%= msg %></li>
-#    <% end %>
-#    </ul>
-#  </div>
-#<% end %>
- content_for :scripts do
  = javascript_include_tag 'deathstare/new_test_session'
.row
  .col-md-8
    -# Test form
    .row
      .col-md-offset-3.col-md-9
        %h1 New Test Session

    .row
      = form_for @test_session, url: test_sessions_path, html: {class: 'form-horizontal', role: 'form'} do |f|
        - if @test_session.errors.any?
          .alert.alert-danger
            - @test_session.errors.full_messages.each do |msg|
              %p= msg

        .form-group#test_names
          = f.label :test_names, 'Tests', class: 'col-md-3 control-label'
          %ul.col-md-8{:style => "list-style:none"}
            - Deathstare::Suite.suites.each do |suite|
              - suite.test_names.each do |test_name|
                %li{:style=>"white-space:nowrap"}
                  = check_box_tag "test_session[test_names][]", "#{suite.name}##{test_name}", !Rails.env.development?, id:"#{suite.name}_#{test_name}".gsub(/\W/,'_')
                  = label_tag "#{suite.name}_#{test_name}", "#{suite.name}: #{test_name}"
            %li
              %a{:href=>'javascript:testSession.selectAll()'} select all
              &nbsp;|&nbsp;
              %a{:href=>'javascript:testSession.selectNone()'} none
        .form-group
          = f.label :base_url, 'End point', class: 'col-md-3 control-label'
          .col-md-5
            = f.select :base_url, Deathstare::EndPoint.target_urls, {}, class: 'form-control'
          .col-md-4
            %span.help-block
              %a{href:'/end_points'} Manage cached devices
        .form-group
          = f.label :run_time, 'Run time', class: 'col-md-3 control-label'
          .col-md-5
            = f.number_field :run_time, in: 0..1000, step: 1, class: 'form-control'
          .col-md-4
            %span.help-block
              In seconds. Leave at zero to run a single iteration per device.

        .form-group
          = f.label :devices, 'Concurrent devices', class: 'col-md-3 control-label'
          .col-md-5
            = f.number_field :devices, in: 1..1000, step: 1, class: 'form-control'
          .col-md-4
            %span.help-block
              Number of concurrently simulated devices
              %em per instance.
              If you want to simulate a load of, e.g. 10,000 devices total,
              you can do this by running 100 instances with 100 concurrent devices each.

        .form-group
          = f.label :comment, class: 'col-md-3 control-label'
          .col-md-5
            = f.text_area :comment, class: 'form-control'
        .form-group
          = f.label :verbose, class: 'col-md-3 control-label'
          .col-md-5
            = f.check_box :verbose, class: 'form-control'
          .col-md-4
            %span.help-block
              Log the details of successful responses.
              %em Not recommended for large tests.
        .form-group
          .col-md-offset-3.col-md-5
            = f.submit 'Go!', class: 'btn btn-primary form-control'

  - if Rails.env.production?
    .col-md-4
      -# Heroku concurrent instance selection
      .row
        .col-md-offset-1.col-md-11
          %h2 Parallel Instances
      .clearfix
      = form_for :concurrent_instances, url: concurrent_instances_path, method: :put, html: {role: 'form', id: 'concurrent-instances-form'} do |f|
        .row
          .col-md-offset-1.col-md-11
            = f.label :requested
        .row
          .col-md-offset-2.col-md-10.text-center
            = f.text_field :requested, class: 'dial', value: 0, 'data-fgColor'=>"#428BCA",'data-angleOffset'=>-125,'data-angleArc'=>250
          .col-md-offset-2.col-md-10.text-center
            = f.button class: 'btn btn-primary ladda-button', id: 'make-it-so-button', 'data-style'=>'expand-right' do
              %span.ladda-label Make it so!

        .row
          .col-md-offset-1.col-md-11
            = f.label :actual, 'Instances up'
        .row
          .col-md-offset-2.col-md-10.text-center
            = f.text_field :actual, class: 'dial', value: 0, 'data-fgColor'=>'#5CB85C','data-readOnly'=>true,'data-angleOffset'=>-125,'data-angleArc'=>250

app/views/deathstare/test_sessions/show.html.haml
%h1
  = "Test session #{@test_session.id} started:"
  = relative_date @test_session.created_at

= render :partial => 'deathstare/test_sessions/details'

- if @test_session.cancelled?
  %p
    Session cancelled:
    = relative_date @test_session.cancelled_at
- elsif @test_session.ended?
  %p
    Session ended:
    = relative_date @test_session.ended_at
- else
  %p= link_to 'Cancel', cancel_test_session_path(@test_session), method:'POST'

%p= link_to 'Error Log', errors_test_session_test_results_path(@test_session)

-if @test_session.verbose?
  %p= link_to 'Result Log', test_session_test_results_path(@test_session)

- suites = @test_session.suite_names.present? ? @test_session.suite_names : Deathstare::Suite.suites.map(&:to_s)
- suites.each do |suite|

  %h2= suite
  %p Axis units are milliseconds
  -# See: http://support.metrics.librato.com/knowledgebase/articles/59534-how-to-embed-charts-in-your-own-application
  - if @live_instrument_ids[suite].present?
    %p
      = link_to "Librato Instrument page for: #{suite}", "https://metrics.librato.com/instruments/#{@live_instrument_ids[suite]}", target: '_blank'

    .librato-metrics{'data-instrument_id' => @live_instrument_ids[suite], 'data-duration' => '1800', 'data-source' => "test_session_#{@test_session.id}"}
  - else
    %p{'data-instrument_name'=>suite}
      Waiting for tests to start and generate data...

= javascript_include_tag "https://sdk.librato.com/librato-sdk-v0.3.0-min.js", 'data-librato_email' => Deathstare.config.librato_email, 'data-librato_token' => Deathstare.config.librato_api_token

:javascript
  window.liveInstrumentIds = #{@live_instrument_ids.to_json};
  function pollInstruments() {
    if (Object.keys(liveInstrumentIds).length == #{@test_session.suite_names.length}) {
      console.log('All expected instruments reporting --> stop polling');
      return; // got at many instruments as expected (one per suite), no need to poll
    }
    console.log('pollingInstruments');
    $.getJSON('#{test_session_path(@test_session)}',
      function(latestInstruments) {
        for (var instrument in latestInstruments) {
          if (!liveInstrumentIds.hasOwnProperty(instrument)) {
            // new property that wasn't there before --> reload
            window.location.reload(true);
          }
        }
      }
    );
    setTimeout(pollInstruments, 5000);   // poll every 5 secs till all instruments are defined
  }
  $(function(){
    setTimeout(pollInstruments, 2000);
  });
  