config/routes.rb
Deathstare::Engine.routes.draw do

  root 'test_sessions#new'

  # don't need :new since we already have root pointing at it
  resources :test_sessions, path:'sessions', only: [:create, :index, :show, :destroy] do
    collection do
      post :clear
    end
    member do
      get :stream
      post :cancel
    end
    resources :test_results, path:'results', only:[:index] do
      collection do
        get :errors
      end
    end
  end

  resources :end_points, only:[:index] do
    member do
      post :reset
    end
  end

  resource :concurrent_instances, only: [:show, :update]

  get 'login' => 'login#new'
  get '/auth/:provider/callback' => 'login#create'
  get 'logout' => 'login#destroy'
  get 'not_signed_in' => 'base#not_signed_in'

  #require 'sidekiq/web'

  #get '/sidekiq' => Sidekiq::Web.new

end

app/models/deathstare/end_point.rb
module Deathstare
  # Represents a single target end point. Multiple {TestSession} instances with the same base URL
  # will share an end point. End points are used to manage cached {UpstreamSession} records.
  class EndPoint < ActiveRecord::Base
    # Get a list of target URLs, this is used in the "End point" drop down in the web dashboard.
    # @return [Array<String>] list of end points
    def self.target_urls
      Deathstare.config.target_urls.dup.tap do |urls|
        urls.unshift 'http://localhost:3000' if Rails.env.development?
        urls.unshift 'http://test.host' if Rails.env.test?
      end
    end

    validates :base_url, inclusion: target_urls
    before_validation :set_defaults

    has_many :test_sessions, :dependent => :delete_all
    has_many :upstream_sessions, :dependent => :delete_all

    # Generate random client devices until the cache has the requested amount.
    # If there are already enough devices in the cache this will be a no-op.
    #
    # @param device_count [Integer] number of devices to create
    # @yieldparam progress [String] periodically yields progress for logging
    # @return [void]
    def generate_devices device_count
      return if upstream_sessions.count >= device_count
      print "Generating #{device_count} devices..." if Rails.env.development?
      needed_devices = device_count - upstream_sessions.count
      needed_devices.times.each do |i|
        generate_upstream_session
        report_progress = (needed_devices >= 10) && (i % (needed_devices/10).to_i == 0)
        yield "Generated #{i} devices." if report_progress && block_given?
      end
      puts 'done.' if Rails.env.development?
    end

    # Ensure every generate client device has a session token, register and login
    # the ones that don't. This method blocks until it's completed.
    #
    # @param client [Client]
    # @param success [Proc] success callback
    # @param failure [Proc] failure callback
    # @return [void]
    def register_and_login_devices client, success=nil, failure=nil, &callback
      success ||= callback
      upstream_sessions.state(nil).each do |session|
        session.register_and_login(client).then success, failure
      end
      client.run
    end

    # Clear the upstream session cache. This is needed whenever the upstream end point is reset.
    # @return [void]
    def clear_upstream_sessions
      upstream_sessions.delete_all
    end

    private

    def generate_upstream_session
      session = nil
      until session && session.save # make sure we get a valid device
        session = (Deathstare.config.upstream_session_type || UpstreamSession).generate(self)
      end
      session
    end

    def set_defaults
      self.base_url = self.class.target_urls.first if self.base_url.blank?
    end
  end
end

app/models/deathstare/heroku_app.rb
module Deathstare
  class HerokuApp

    # @abstract Heroku doesn't reject people from logging in even if they aren't members on the app
    #   They'll get an API token anyway. However, every subsequent call to the API fails with a 403
    #   (forbidden) -- that's how we can tell they're not a legit user.
    # @param user [User] -- authenticated User with Heroku OAuth token and/or refresh token
    def self.user_authorized_for_app? user
      HerokuApiV3.get(user: user, url: "/apps/#{Deathstare.config.heroku_app_id}")
      true
    rescue HerokuApiV3::UnauthorizedAppError
      false
    end

    # @param user [User] -- authenticated User with Heroku OAuth token and/or refresh token
    # @param requested [Integer or String] Number of sidekiq workers requested
    def self.scale_sidekiq_workers(user, requested)
      HerokuApiV3.patch(
        user: user,
        url: "/apps/#{Deathstare.config.heroku_app_id}/formation/sidekiq",
        body: {quantity: requested}
      )
    end

    # @param user [User] -- authenticated User with Heroku OAuth token and/or refresh token
    # @return [Integer] Number of sidekiq processes in "up" state
    def self.get_number_running_sidekiq_workers(user)
      # Sadly the formation API doesn't give us the status
      # And the dyno API won't let us query by type :-(
      # So we get all dynos and filter in Ruby
      dynos = HerokuApiV3.get(
        user: user,
        url: "/apps/#{Deathstare.config.heroku_app_id}/dynos"
      )
      dynos.count { |dyno| dyno['type'] == 'sidekiq' && dyno['state'] == 'up' }
    end
  end
end

app/models/deathstare/test_result.rb
require 'yajl'

class Deathstare::TestResult < ActiveRecord::Base
  belongs_to :test_session
  validates :test_session_id, :suite_name, :test_name, presence: true

  class << self
    # @param suite_name [String] Suite name
    # @param test_name [String] Test name
    # @param response [Hash] response hash from DSClient
    def from_response suite_name, test_name, response
      new(
        suite_name: suite_name,
        test_name: test_name,
        messages: response_message(response).tap {|msg| puts(msg) if Rails.env.development? }
      )
    end

    # Create a log message given a response Hash.
    def response_message response
      "%s %s: %s %s (%f)\n%s" % [
        *response[:_response_meta].slice(
          :request_method, :request_url, :status_code, :status_message, :total_time
        ).values,
        Yajl::Encoder.encode(response.except(:_response_meta))
      ]
    end
  end
end

app/models/deathstare/user.rb
module Deathstare
  class User < ActiveRecord::Base

    validates :oauth_provider, :uid, presence: true

  end
end

app/controllers/deathstare/application_controller.rb
module Deathstare
  class ApplicationController < ActionController::Base
    include Deathstare::CurrentUser

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    # This shouldn't be happening any more--> we try to refresh tokens if they're expired or about to expire
    rescue_from HerokuApiV3::ExpiredTokenError, with: :token_expired

    force_ssl if: -> { Rails.env.production? }
    before_action :ensure_signed_in!, except: :not_signed_in # production only

    def not_signed_in
      redirect_to root_path if signed_in?
    end

    protected

    def token_expired
      session[:user_id] = nil
      respond_to do |fmt|
        fmt.html { redirect_to not_signed_in_path, alert: 'Heroku session has expired. Please sign in.' }
        fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
      end
    end

    def can_control_scalability?
      Rails.env.production?
    end

    private

    def ensure_signed_in!
      if !signed_in? && Rails.env.production?
        respond_to do |fmt|
          fmt.html { redirect_to not_signed_in_path, alert: 'Please sign in.' }
          fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
        end
      end
    end
  end
end

app/controllers/deathstare/base_controller.rb
module Deathstare
  class BaseController < ApplicationController
    include Deathstare::CurrentUser

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    # This shouldn't be happening any more--> we try to refresh tokens if they're expired or about to expire
    rescue_from HerokuApiV3::ExpiredTokenError, with: :token_expired

    force_ssl if: -> { Rails.env.production? }
    before_action :ensure_signed_in!, except: :not_signed_in # production only

    def not_signed_in
      redirect_to root_path if signed_in?
    end

    protected

    def token_expired
      session[:user_id] = nil
      respond_to do |fmt|
        fmt.html { redirect_to not_signed_in_path, alert: 'Heroku session has expired. Please sign in.' }
        fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
      end
    end

    def can_control_scalability?
      Rails.env.production?
    end

    private

    def ensure_signed_in!
      if !signed_in? && Rails.env.production?
        respond_to do |fmt|
          fmt.html { redirect_to not_signed_in_path, alert: 'Please sign in.' }
          fmt.json { render json: {error: 'Heroku session has expired. Please sign in.'}, status: 401 }
        end
      end
    end
  end
end

app/controllers/deathstare/concurrent_instances_controller.rb
module Deathstare
  class ConcurrentInstancesController < Deathstare::BaseController
    def show
      if signed_in?
        num = HerokuApp.get_number_running_sidekiq_workers current_user
        render json: {actual: num}, status: 200
      elsif Rails.env.development?
        render json: {actual: 1}, status: 200
      else
        render json: {actual: 0}, status: 200
      end
    end

    def update
      if can_control_scalability?
        HerokuApp.scale_sidekiq_workers(current_user, params[:requested])
        render json: {requested: params[:requested]}, status: 200
      else
        render json: {error: 'Can only scale workers in production environment'}, status: 412
      end
    end

  end
end

app/controllers/deathstare/end_points_controller.rb
module Deathstare
  class EndPointsController < BaseController
    def index
      @end_points = EndPoint.all
    end

    def reset
      end_point.clear_upstream_sessions
      flash[:notice] = "Cleared cache of devices and sessions for #{end_point.base_url}."
      redirect_to end_points_path
    end

    private

    def end_point
      EndPoint.find params[:id]
    end
  end
end

app/controllers/deathstare/login_controller.rb
module Deathstare
  class LoginController < BaseController

    skip_before_action :ensure_signed_in!, except: :destroy

    def new
      redirect_to '/auth/heroku'
    end

    def create
      omniauth = request.env['omniauth.auth']
      @current_user = User.find_or_create_by!(oauth_provider: omniauth['provider'], uid: omniauth['uid'])
      @current_user.token = omniauth['credentials']['token']
      @current_user.token_expires_at = !!omniauth['credentials']['expires'] ? Time.at(omniauth['credentials']['expires_at']) : nil
      @current_user.refresh_token = omniauth['credentials']['refresh_token']
      @current_user.save!
      if HerokuApp.user_authorized_for_app?(@current_user)
        session[:user_id] = @current_user.id
        redirect_to root_path, notice: 'Signed in with Heroku'
      else
        @current_user.authorized_for_app = false
        @current_user = nil
        session[:user_id] = nil
        redirect_to root_path, alert: "You are not authorized on this app. If you're a member of Cloud City Development, talk to the administrator."
      end
    end

    def destroy
      @current_user = nil
      session[:user_id] = nil
      redirect_to root_path, notice: 'Ended Heroku OAuth Session'
    end
  end
end

app/controllers/deathstare/test_results_controller.rb
module Deathstare
  class TestResultsController < BaseController
    def index
      @title = "Result Log"
      @test_session = test_session
      @test_results = @test_session.test_results.order('created_at DESC').paginate(page: params[:page], per_page: 100)
    end

    def errors
      @title = "Error Log"
      @test_session = test_session
      @test_results = @test_session.test_errors.order('created_at DESC').paginate(page: params[:page], per_page: 100)
      render action:'index'
    end

    private

    def test_session
      TestSession.find params[:test_session_id]
    end
  end
end

app/controllers/deathstare/test_sessions_controller.rb
module Deathstare
  require 'librato/librato_app'

  class TestSessionsController < BaseController
    before_action :load_resource, only: [:show, :stream, :cancel, :destroy]

    def index
      @test_sessions = TestSession.order(id: :desc).paginate(page:params[:page])
      # TODO: List here links to the show pages of previous runs
    end

    def new
      @test_session = TestSession.new_with_defaults
    end

    def create
      params.permit!

      worker_count = \
        if Rails.env.development? || Rails.env.test?
          1
        elsif signed_in?
          HerokuApp.get_number_running_sidekiq_workers(current_user)
        else
          0
        end

      if worker_count == 0
        flash.alert = "Start at least one worker instance per Suite being tested."
        redirect_to action: 'new'
        return
      end

      @test_session = TestSession.create(params[:test_session].merge(workers:worker_count, user:current_user))
      if @test_session.persisted?
        @test_session.enqueue
        redirect_to @test_session
      else
        flash.alert = "Failed to create session: #{@test_session.errors.full_messages.join(' ')}"
        redirect_to action: 'new'
      end
    end

    def show
      load_resource
      @live_instrument_ids = LibratoApp.create_or_update_instruments(@test_session.suite_names)
      respond_to do |format|
        format.html { render 'show' }
        format.json { render json: @live_instrument_ids }
      end
    end

    def cancel
      if @test_session.cancel_session
        flash.notice = "You've cancelled session ##{@test_session.id}."
      else
        flash.alert = "Failed to cancel session ##{@test_session.id}!"
      end
      redirect_to @test_session
    end

    def destroy
      if !@test_session.ended?
        flash.alert = "This session is still running, cancel it first."
      elsif @test_session.destroy
        flash.notice = "Removed session ##{@test_session.id}."
      else
        flash.alert = "Failed to remove session ##{@test_session.id}."
      end
      redirect_to action:'index'
    end

    def clear
      if Deathstare::TestSession.running.any?
        flash.alert = "There is a running session, cancel it first."
        redirect_to action:'index'
      else
        Deathstare::TestSession.destroy_all
        flash.notice = "Removed all previous sessions."
        redirect_to action:'new'
      end
    end

    private

    def load_resource
      @test_session = TestSession.find(params[:id])
    end

  end
end

app/helpers/deathstare/application_helper.rb
module Deathstare
  module ApplicationHelper
    # Return HTML to support a pretty-printed date.
    #
    # @param date [DateTime] some date in the past
    # @return [String] HTML span representing a friendly-formatted date
    def relative_date date
      %[<span class="relative-date" title="#{date.iso8601}">#{date}</span>].html_safe
    end

    # @param test_session [TestSession] test session
    # @return [String] Friendly list of suite classes, or "All"
    def suites test_session
      test_session.suite_names.join(', ').tap{|t| t.prepend('All') if t.empty? }
    end
  end
end

app/helpers/deathstare/base_helper.rb
module Deathstare
  module BaseHelper
    # Return HTML to support a pretty-printed date.
    #
    # @param date [DateTime] some date in the past
    # @return [String] HTML span representing a friendly-formatted date
    def relative_date date
      %[<span class="relative-date" title="#{date.iso8601}">#{date}</span>].html_safe
    end

    # @param test_session [TestSession] test session
    # @return [String] Friendly list of suite classes, or "All"
    def suites test_session
      test_session.suite_names.join(', ').tap{|t| t.prepend('All') if t.empty? }
    end
  end
end

app/views/layouts/deathstare/_flash.html.haml
- if flash[:notice].present?
  .alert.alert-success.alert-dismissable
    %button.close{type: 'button', 'data-dismiss'=>'alert', 'aria-hidden'=>true} &times;
    = flash[:notice]
- elsif flash[:alert].present?
  .alert.alert-danger.alert-dismissable
    %button.close{type: 'button', 'data-dismiss'=>'alert', 'aria-hidden'=>true} &times;
    = flash[:alert]

-#For JS errors
.js-templates
.alert.alert-success.alert-dismissable.js-alert-success-template{style: 'display: none'}
  %button.close{type: 'button', 'data-dismiss'=>'alert', 'aria-hidden'=>true} &times;
  %span
.alert.alert-danger.alert-dismissable.js-alert-error-template{style: 'display: none'}
  %button.close{type: 'button', 'data-dismiss'=>'alert', 'aria-hidden'=>true} &times;
  %span

app/views/layouts/deathstare/_login_logout_links.html.haml
- if signed_in?
  %p.navbar-text.pull-right
    = link_to 'Sign Out', logout_path, class: 'navbar-link'
- else
  = button_to('/auth/heroku', method: :get, class: 'btn btn-info navbar-btn navbar-right')  do
    Sign in with
    %img{src: 'https://d1lpkba4w1baqt.cloudfront.net/heroku-logo-light-88x31.png'}

app/views/layouts/deathstare/application.html.haml
!!!
%html
  %head
    %title Deathstare Test Dashboard
    = stylesheet_link_tag    'deathstare/application', media: 'all'
    = javascript_include_tag 'deathstare/application'
    = csrf_meta_tags
    =javascript_tag '$(function() {$(".relative-date").prettyDate()})'
  %body{'data-environment'=>Rails.env}
    .navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
          -if Deathstare::TestSession.running.any?
            = link_to "Testing in Progress", test_session_path(Deathstare::TestSession.running.first),
              class: ['navbar-brand', 'currently-running']
          -else
            = link_to 'Test Dashboard', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          - if Rails.env.development? || signed_in?
            %ul.nav.navbar-nav
              %li
                = link_to 'New Test Run', root_path
              %li
                = link_to 'Previous Runs', test_sessions_path
              %li
                = link_to 'All Results (Librato)', 'https://metrics.librato.com/instruments', target: '_blank'
              %li
                = link_to 'API Docs', '/doc/', target: '_blank'
              %li
          = render partial: 'layouts/deathstare/login_logout_links'

    .container
      = render partial: 'layouts/deathstare/flash'

      = yield

app/views/layouts/deathstare/base.html.haml
!!!
%html
  %head
    %title Deathstare Test Dashboard
    = stylesheet_link_tag    'deathstare/application', media: 'all'
    = javascript_include_tag 'deathstare/application'
    = yield :scripts
    = javascript_tag '$(function() {$(".relative-date").prettyDate()})'
    = csrf_meta_tags
  %body{'data-environment'=>Rails.env}
    .navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
          -if Deathstare::TestSession.running.any?
            = link_to "Testing in Progress", test_session_path(Deathstare::TestSession.running.first),
              class: ['navbar-brand', 'currently-running']
          -else
            = link_to 'Test Dashboard', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          - if Rails.env.development? || signed_in?
            %ul.nav.navbar-nav
              %li
                = link_to 'New Test Run', root_path
              %li
                = link_to 'Previous Runs', test_sessions_path
              %li
                = link_to 'All Results (Librato)', 'https://metrics.librato.com/instruments', target: '_blank'
              %li
                = link_to 'API Docs', '/doc/', target: '_blank'
              %li
          = render partial: 'layouts/deathstare/login_logout_links'

    .container
      = render partial: 'layouts/deathstare/flash'

      = yield